### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by quiriss** [quiriss/iron-magic#2]
Sprint #1 

DEADLINE 30 sierpień

Kirill:
- [ ] poszukać modele
- [ ] poprawić modele
- [ ] zintegrować 3d modele z projektem Damiana

Damian:
- [x] napisać wstępny projekt "strzelanki samolotowej"
- [x] przesłać projekt na github'a

**Comment by butwulkan** [comment]
Zrobiłem commita, ale oczywiście go nie widać na serwerze.
Thanks obama

**Comment by quiriss** [comment]
![U CAN DO IT](http://i.imgur.com/KICjocl.gif)

**Comment by butwulkan** [comment]
![ican](https://i.imgflip.com/q4wac.jpg)
